### PR TITLE
fix: Nested validation to run schema validation

### LINKED ISSUE #37: Nested validation not working correctly
Nested validation does not call validate function from nested schema.

### PR DESCRIPTION
**Pull request by RaduMolnar99**
Closes #37

### CODE REVIEW

File: src/schema/schema.ts [hunk 1]
```diff
@@ -110,13 +110,25 @@ export class Schema<T, Context = unknown> {
...
+          throw e;
+        }
+      }
 
       if (Object.keys(validatorErrors).length !== 0) {
         errors[validatorProperty] = validatorErrors;
         continue;
       }
 
+      await validator.validate();
```
Comment (dariusmb) [inline src/schema/schema.ts:130]: Why is this called 2 times?

**Review by dariusmb — CHANGES_REQUESTED** [review]

**Review by dariusmb — APPROVED** [review]
